CREATE TABLE "orders" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_date" timestamp DEFAULT now() NOT NULL,
	"customer_name" text NOT NULL,
	"address_1" text NOT NULL,
	"address_2" text,
	"city_state_zip" text NOT NULL,
	"phone" text,
	"email" text,
	"description" text,
	"special_requests" text,
	"frame_sku" text NOT NULL,
	"chop_only" boolean DEFAULT false NOT NULL,
	"width" numeric NOT NULL,
	"height" numeric NOT NULL,
	"mat_border_all" numeric,
	"mat_border_left" numeric,
	"mat_border_right" numeric,
	"mat_border_top" numeric,
	"mat_border_bottom" numeric,
	"mat_1_sku" text,
	"mat_1_reveal" numeric,
	"mat_2_sku" text,
	"mat_2_reveal" numeric,
	"mat_3_sku" text,
	"extra_mat_openings" integer DEFAULT 0 NOT NULL,
	"acrylic_type" text DEFAULT 'Standard' NOT NULL,
	"backing_type" text DEFAULT 'White Foam' NOT NULL,
	"print_paper" boolean DEFAULT false NOT NULL,
	"print_paper_type" text,
	"dry_mount" boolean DEFAULT false NOT NULL,
	"print_canvas" boolean DEFAULT false NOT NULL,
	"print_canvas_wrap_style" text,
	"engraved_plaque" boolean DEFAULT false NOT NULL,
	"engraved_plaque_size" text,
	"leds" boolean DEFAULT false NOT NULL,
	"shadowbox_fitting" boolean DEFAULT false NOT NULL,
	"additional_labor" boolean DEFAULT false NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"item_total" numeric(10, 2) NOT NULL,
	"shipping" numeric(10, 2) NOT NULL,
	"sales_tax" numeric(10, 2),
	"discount_percent" integer DEFAULT 0 NOT NULL,
	"total" numeric(10, 2) NOT NULL,
	"deposit" numeric(10, 2),
	"balance" numeric(10, 2) NOT NULL
);
